[parity]
chain = "/home/parity/.local/share/io.parity.ethereum/spec.json"
db_path = "/root/data"
keys_path = "/root/keystore"

[rpc]
cors = ["all"]
port = 8545
interface = "all"
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]

[websockets]
disable = true

[network]
port = 30300
reserved_peers="/home/parity/.local/share/io.parity.ethereum/bootnodes.txt"
